
name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Descargar el repositorio
      - name: Checkout
        uses: actions/checkout@v4

      # 2️⃣ Extraer metadata de la imagen
      - name: Extract Docker image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: joce22/configuracion_docker  # 🔹 tu usuario y repo en Docker Hub

      # 3️⃣ Login en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}   # 🔹 secrets, no vars
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4️⃣ Configurar Buildx (para construir multi-plataforma si quieres)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 5️⃣ Construir y subir la imagen
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
          provenance: true
          sbom: true
